Add Code tab to Heading page
dxc-technology/halstack-react pull request #1024
Opened 2022-05-31 15:30 UTC by Lisa159

2022-06-02 07:28 UTC, raquelarrojo requested changes

2022-06-02 07:28 UTC, raquelarrojo commented on website/screens/components/heading/code/examples/basic.ts
> +  );
Add inset instead of div.

2022-06-03 07:44 UTC, Lisa159 commented on website/screens/components/heading/code/examples/basic.ts
> +  );
Done

2022-06-03 11:37 UTC, raquelarrojo approved these changes

2022-06-03 11:37 UTC, merged