Add Code tab to Number Input page
dxc-technology/halstack-react pull request #1030
Opened 2022-06-01 13:55 UTC by Lisa159

2022-06-02 10:13 UTC, raquelarrojo requested changes

2022-06-03 10:41 UTC, Lisa159 commented on website/pages/components/number-input/index.tsx
>    return (
Done

2022-06-03 10:41 UTC, Lisa159 commented on website/screens/components/number-input/code/examples/basic.ts
> +    </DxcInset>
Done

2022-06-03 10:41 UTC, Lisa159 commented on website/screens/components/number-input/code/NumberInputCodePage.tsx
> +        content: (
Done

2022-06-03 10:41 UTC, Lisa159 commented on website/screens/components/number-input/code/examples/basic.ts
> +import {
Done

2022-06-03 10:42 UTC, Lisa159 commented on website/screens/components/number-input/code/NumberInputCodePage.tsx
> +        content: (
Done

2022-06-03 10:42 UTC, Lisa159 commented on website/screens/components/number-input/code/examples/controlled.ts
> +        value={value}
Done

2022-06-03 10:43 UTC, Lisa159 commented on website/screens/components/number-input/code/examples/uncontrolled.ts
> +          ref={inputRef}
Done

2022-06-03 10:43 UTC, Lisa159 commented on website/screens/components/number-input/code/examples/error.ts
> +    </DxcInset>
Done

2022-06-03 11:51 UTC, raquelarrojo requested changes

2022-06-03 11:51 UTC, raquelarrojo commented on website/screens/components/number-input/code/examples/errorHandling.ts
> +        min={5}
As this check is done in the onChange and onBlur, here we can keep it as: `error={errorMessage}`.

2022-06-03 11:57 UTC, raquelarrojo approved these changes

2022-06-03 11:57 UTC, merged