Added Accordion code page
dxc-technology/halstack-react pull request #1041
Opened 2022-06-03 12:59 UTC by raquelarrojo

Closes [#981](https://github.com/dxc-technology/halstack-react/issues/981).

2022-06-13 07:10 UTC, jsuarezgonz requested changes

2022-06-13 07:10 UTC, jsuarezgonz commented on website/screens/components/accordion/usage/examples/assistiveText.ts
> +        padding="medium"
Please remove this padding and change the DxcInset space.

2022-06-13 07:10 UTC, jsuarezgonz commented on website/screens/components/accordion/usage/examples/behaviorAndInteraction.ts
> +          padding="medium"
Please remove this padding and change the DxcInset space.

2022-06-14 11:45 UTC, raquelarrojo commented on website/screens/components/accordion/code/examples/uncontrolledAccordion.ts
> +        padding="medium"
Done!

2022-06-14 11:45 UTC, raquelarrojo commented on website/screens/components/accordion/code/examples/controlledAccordion.ts
> +        padding="medium"
Done!

2022-06-15 06:29 UTC, jsuarezgonz approved these changes

2022-06-15 06:29 UTC, merged