Adding Code tab for pagination component and some fixes in button and alert
dxc-technology/halstack-react pull request #1051
Opened 2022-06-06 13:49 UTC by jsuarezgonz

Closes #1035

2022-06-07 07:42 UTC, raquelarrojo requested changes

2022-06-07 07:42 UTC, raquelarrojo commented on website/screens/components/alert/code/examples/basicUsage.ts
> +const code = `() => {
Remove DxcStack unnecessary import.

2022-06-09 15:22 UTC, jsuarezgonz commented on website/screens/components/alert/code/examples/basicUsage.ts
> +const code = `() => {
Done.

2022-06-10 11:22 UTC, raquelarrojo approved these changes

2022-06-10 11:22 UTC, merged