Jialecl removing material checkbox
dxc-technology/halstack-react pull request #1193
Opened 2022-07-22 11:46 UTC by Jialecl

2022-07-26 12:49 UTC, raquelarrojo requested changes
- When the checkbox is checked, if we make hover on the label, the checkbox should not be hovered. We cold add a test of this in Chromatic.
- When the checkbox is checked/unchecked, it should not be focused.

2022-07-26 12:54 UTC, raquelarrojo commented on lib/src/checkbox/Checkbox.tsx
> +          type="checkbox"
Already done.

2022-07-27 09:56 UTC, Jialecl commented
> * When the checkbox is checked, if we make hover on the label, the checkbox should not be hovered. We cold add a test of this in Chromatic.

Since the unchecked checkbox was reacting to the label being hovered, we pondered if the checked checkbox should also change state and it was decided to add it.

2022-08-01 13:14 UTC, raquelarrojo commented on lib/src/checkbox/Checkbox.tsx
>      <ThemeProvider theme={colorsTheme.checkbox}>
This `labelPosition` check is still done twice: in `labelComponent` and in the return. Please keep it only in the return.

2022-08-01 13:20 UTC, raquelarrojo requested changes
There should not be any visual changes with the new version without material. We should fix this change:

![image](https://user-images.githubusercontent.com/10975289/182157103-42312c8c-fe77-4e74-a9db-2ae0d7cbcb80.png)

2022-08-03 07:23 UTC, Jialecl commented on lib/src/checkbox/Checkbox.tsx
>      <ThemeProvider theme={colorsTheme.checkbox}>
The one that is done inside `labelComponent` is to put optional in the correct position. And the one that is done where the `labelComponent` is rendered is to position the `labelComponent` itself.

2022-09-01 10:00 UTC, closed without merging