Removing Material from slider
dxc-technology/halstack-react pull request #1244
Opened 2022-08-22 10:41 UTC by Jialecl

2022-09-06 12:48 UTC, marcialfps requested changes
### Other changes
- I think we should be consistent in how we implement all the components. In your case you are setting the type next to the styled component, I propose you create types for each one naming them as `XXXXPropsType`.

- The disabled tracker changes its styles when clicked.
![image](https://user-images.githubusercontent.com/35959222/188638104-1602cac0-e8be-404d-ae39-837560fe9e82.png)

- Add new tests:
  - Test case for all accessibility attributes.
  - Test cases for all [keyboard interactions](https://www.w3.org/WAI/ARIA/apg/patterns/slider/).
  - Test case we saw in the call: `minValue={5} maxValue={50} step={10}`. Verify that the maximum value is 45.

2022-09-15 07:47 UTC, Jialecl commented on lib/src/slider/Slider.tsx
> +  top: calc(50% - 2px);
I have decided that the best solution is to change the height to 100% and use displayÑflex to align the marks.

2022-09-20 08:05 UTC, marcialfps requested changes
- As I said in the previous comment:
  - Add test case for **ALL** accessibility attributes, including: `aria-labelledby`, `aria-orientation`, `aria-valuemax`, `aria-valuemin`, `aria-valuenow`. This should be added to the first test case, not others. If you need an example, take a look to the first test case from Radio Group component.
  - The disabled tracker changes its styles when clicked.
![image](https://user-images.githubusercontent.com/35959222/191202687-15597a0e-430e-4438-b44c-e6ec87edf65f.png)

2022-09-20 08:05 UTC, marcialfps commented on lib/src/slider/Slider.tsx
> +type LabelProps = { disabled: boolean; backgroundType: "dark" | "light" };
Rename to `LabelPropsType`.

2022-09-20 08:05 UTC, marcialfps commented on lib/src/slider/Slider.tsx
> +const Slider = styled.input<SliderProps>`
Rename to `SliderInput`.

2022-09-20 08:05 UTC, marcialfps commented on lib/src/slider/Slider.tsx
> +type SliderProps = {
Rename to `SliderInputPropsType`.

2022-09-20 08:05 UTC, marcialfps commented on lib/src/slider/Slider.tsx
> +type MarksContainerProps = { isFirefox: boolean };
Rename to `MarksContainerPropsType`.

2022-09-20 08:05 UTC, marcialfps commented on lib/src/slider/Slider.tsx
> +type TickMarkProps = { stepPosition: number; disabled: boolean; backgroundType: "dark" | "light" };
Rename to `TickMarkPropsType`.

2022-09-20 15:27 UTC, marcialfps commented on lib/src/slider/Slider.test.js
>    test("Calls correct function onDragEnd", () => {
Add `... when it is uncontrolled`.

2022-09-21 07:43 UTC, marcialfps approved these changes

2022-09-21 07:44 UTC, merged