Fixed navigation using repeated sublinks in QuickNav
dxc-technology/halstack-react pull request #1338
Opened 2022-10-19 09:50 UTC by Lisa159

**Checklist**
_(Check off all the items before submitting)_
- [x] Build process is done without errors and all tests pass in `/lib` directory.
- [x] Self-reviewed the code prior to submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Purpose**
Navigation using sublinks wasn't working fine if the sublink text is the same as other sublink of other section in the QuickNav component.

**Description**
Added parent label to sublinks `href`. So for example, if parent label is `overview` and sublink is `introduction`, navigation for sublink will be `overview-introduction`.

Besides, updated stories with working links and sublinks. Removed unused `id` prop from array.

**Screenshots**
![image](https://user-images.githubusercontent.com/34685461/196657815-c3e5448c-cde1-486c-a0e1-7c359a5f422e.png)

![image](https://user-images.githubusercontent.com/34685461/196657654-9c5164a5-7127-4411-80ae-9f7ebde8b038.png)

**Closes #1323**

2022-10-21 10:22 UTC, raquelarrojo requested changes

2022-10-21 10:22 UTC, raquelarrojo commented on lib/src/quick-nav/QuickNav.stories.tsx
>  const links = [
Please remove `id` from `defaultLinks` also (line 14).

2022-10-25 07:09 UTC, Lisa159 commented on lib/src/quick-nav/QuickNav.stories.tsx
>  const links = [
Done!

2022-10-25 07:56 UTC, raquelarrojo approved these changes

2022-10-25 07:56 UTC, merged