[File Input] Single file item styles update
dxc-technology/halstack-react pull request #1377
Opened 2022-11-10 16:20 UTC by GomezIvann

**Checklist**
_(Check off all the items before submitting)_
- [ ] Build process is done without errors and all tests pass in `/lib` directory.
- [ ] Self-reviewed the code prior to submitting.
- [ ] Meets accessibility standards.
- [ ] Added/updated documentation to `/website` as needed.
- [ ] Added/updated tests as needed.

**Description**
A clear and concise description of the change.

**Closes #`issue-number`**

2022-11-17 12:36 UTC, GomezIvann commented
> * In `filedrop` mode, please change the padding of the `ButtonContainer` to `4px 12px 4px 4px` instead of `2px 12px 2px 3px` as specified in the guidelines.
> 
> Current implementation: ![image](https://user-images.githubusercontent.com/10975289/202401390-6c2c616b-524e-47b1-92fb-c9a133727096.png)
> 
> Guidelines: ![image](https://user-images.githubusercontent.com/10975289/202401087-13a84235-f53f-4f7b-8c6f-d0ebbb286546.png)
> 
> * In `filedrop` and `dropzone` modes, if it is not multiple and the file has an error, the error is not shown.
> 
> ![image](https://user-images.githubusercontent.com/10975289/202403399-d36e25b3-3043-4376-955f-275af00ad532.png)
> 
> ![image](https://user-images.githubusercontent.com/10975289/202403479-9dfe5163-ad6c-46f3-9b6c-8cb8ee652b18.png)
> 
> I think the error should be shown like this: ![image](https://user-images.githubusercontent.com/10975289/202403568-77f71926-c399-4665-8e1e-423f74c8dd91.png)

Are you sure the padding is `4px 12px 4px 4px`? I mean, the styles of Alex say that the distance is `4px` taking into account the border (`4px` - `1px` of border = `3px` of padding), am I right?

2022-11-18 07:56 UTC, raquelarrojo commented
> > * In `filedrop` mode, please change the padding of the `ButtonContainer` to `4px 12px 4px 4px` instead of `2px 12px 2px 3px` as specified in the guidelines.
> > 
> > Current implementation: ![image](https://user-images.githubusercontent.com/10975289/202401390-6c2c616b-524e-47b1-92fb-c9a133727096.png)
> > Guidelines: ![image](https://user-images.githubusercontent.com/10975289/202401087-13a84235-f53f-4f7b-8c6f-d0ebbb286546.png)
> > 
> > * In `filedrop` and `dropzone` modes, if it is not multiple and the file has an error, the error is not shown.
> > 
> > ![image](https://user-images.githubusercontent.com/10975289/202403399-d36e25b3-3043-4376-955f-275af00ad532.png)
> > ![image](https://user-images.githubusercontent.com/10975289/202403479-9dfe5163-ad6c-46f3-9b6c-8cb8ee652b18.png)
> > I think the error should be shown like this: ![image](https://user-images.githubusercontent.com/10975289/202403568-77f71926-c399-4665-8e1e-423f74c8dd91.png)
> 
> Are you sure the padding is `4px 12px 4px 4px`? I mean, the styles of Alex say that the distance is `4px` taking into account the border (`4px` - `1px` of border = `3px` of padding, so the value would be `3px 12px 3px 3px`), am I right?

Yes, I totally agree. Taking a look to the specs, `4px` is the distance with the border. So we could calculate the padding as you say, calc(`4px - dropBorderThickness`), since `dropBorderThickness` is the token for the border width.

2022-11-21 08:32 UTC, raquelarrojo requested changes
When it is `multiple={false}` and it has several files in value, it should show the files like this:

Code:
```
<DxcFileInput
    label="Single file with files in value"
    helperText="Please select files"
    callbackFile={callbackFile}
    value={allFiles}
    multiple={false}
/>
```
![image](https://user-images.githubusercontent.com/10975289/203003771-f3e2e933-af06-4fcf-aa7e-0417cf653881.png)

Now they are shown:
![image](https://user-images.githubusercontent.com/10975289/203003993-8d9f2284-8917-4b14-81cd-8ffe2c54c2ba.png)

2022-11-21 15:08 UTC, raquelarrojo approved these changes

2022-11-21 15:08 UTC, merged