Fix dropdown menu resize when label changes
dxc-technology/halstack-react pull request #1380
Opened 2022-11-15 12:07 UTC by marcialfps

**Checklist**
_(Check off all the items before submitting)_
- [x] Build process is done without errors and all tests pass in `/lib` directory.
- [x] Self-reviewed the code prior to submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Description**
`label` prop is included in the `useEffect` that executes the resize of the dropdown menu.

**Screenshots**
Screenshots from this code:
```
const [label, setLabel] = useState("1");

  useEffect(() => {
    new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve("foo");
      }, 1000);
    }).then(() => {
      setLabel("vicrodriguezgu");
    });
  }, []);

  return (
    <>
      <ExampleContainer>
        <Title title="Default" theme="light" level={4} />
        <DxcDropdown label={label} options={options} onSelectOption={(value) => {}} />
      </ExampleContainer>
    </>
  );
```

Before:
![image](https://user-images.githubusercontent.com/35959222/201915645-8855fa73-8581-413b-a68b-84658587ae24.png)

After:
![image](https://user-images.githubusercontent.com/35959222/201915518-f200bf88-b9d7-4385-b914-c8d1734dc8c0.png)

**Closes #1374**

2022-11-17 11:46 UTC, GomezIvann requested changes

2022-11-17 11:46 UTC, GomezIvann commented on lib/src/dropdown/Dropdown.tsx
> +  }, [label]);
I don't think this is the right approach. Inside the array of dependencies should only go the `scope variables that are used by the side effect and change over time. From [React docs](https://reactjs.org/docs/hooks-reference.html#useeffect):

![image](https://user-images.githubusercontent.com/44321109/202435448-9d79b8b7-690c-4043-9843-deba2c185e1c.png)

The `label` variable is not been used by the `useEffect` so it cannot go inside the dependency array, even if its change indirectly affects the effect. Also, that was not the intended purpose of this side effect (it has to be executed only once to add the event to the listeners of the window, so when the viewport changes the list also changes).

2022-11-17 11:46 UTC, GomezIvann commented on lib/src/dropdown/Dropdown.tsx
> +  }, [label]);
The problem here (if I understood Viti's issue correctly) is that first the dropdown renders and then changes its label with the user's username, so the list needs to adapt to that dynamic change. This is a different side effect which needs to be approached in a specific way. Maybe we should use the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) for this purpose.

2022-11-25 08:52 UTC, marcialfps commented
Closing this PR in order to merge the solution purposed by @GomezIvann .

2022-11-25 08:52 UTC, closed without merging