Several Flex enhancements
dxc-technology/halstack-react pull request #1594
Opened 2023-05-09 07:39 UTC by raquelarrojo

**Checklist**
_(Check off all the items before submitting)_
- [x] Build process is done without errors and all tests pass in `/lib` directory.
- [x] Self-reviewed the code prior to submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Description**

- Include MDN link to Flex props in documentation.
- Restrict the values of the gap property of the Flex component.
- Type comments missing in Flex component.

**Closes #1481 #1568 #1592**

2023-05-10 15:06 UTC, GomezIvann requested changes

2023-05-11 07:44 UTC, raquelarrojo commented on lib/src/flex/types.ts
>  export type StyledProps = CommonProps & {
Totally agree! I will remove it

2023-05-11 07:44 UTC, raquelarrojo commented on website/screens/components/flex/code/FlexCodePage.tsx
> +              href="https://developer.mozilla.org/es/docs/Web/CSS/flex-direction"
For sure!

2023-05-11 14:56 UTC, GomezIvann submitted a review, later dismissed

2023-05-12 10:11 UTC, GomezIvann approved these changes

2023-05-16 08:11 UTC, GomezIvann approved these changes

2023-05-16 08:11 UTC, merged