Fix different spec image title in website
dxc-technology/halstack-react pull request #1704
Opened 2023-10-10 12:38 UTC by raquelarrojo

**Checklist**
_(Check off all the items before submitting)_

- [x] Build process is done without errors. All tests pass in the `/lib` directory.
- [x] Self-reviewed the code before submitting.
- [ ] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [ ] Added/updated tests as needed.

**Description**

- Specs images captions are different in all components. Now this is fixed so that all captions follow the same structure.
- Fix several inconsistencies in usage pages.

**Closes #1491**

2023-10-10 13:48 UTC, jsuarezgonz requested changes

2023-10-10 13:48 UTC, jsuarezgonz commented on website/screens/components/accordion/usage/AccordionUsagePage.tsx
> +                    <strong>Left</strong>. Place chevron icon at the end of the
`<em>` tag is missing.

2023-10-11 08:49 UTC, raquelarrojo commented on website/screens/components/accordion/usage/AccordionUsagePage.tsx
> +                    <strong>Left</strong>. Place chevron icon at the end of the
The rest of <em> are removed.

2023-10-11 09:04 UTC, jsuarezgonz approved these changes

2023-10-11 09:04 UTC, merged