Added small footer variant
dxc-technology/halstack-react pull request #1793
Opened 2024-01-31 15:34 UTC by Mil4n0r

**Checklist**
_(Check off all the items before submitting)_

- [x] Build process is done without errors. All tests pass in the `/lib` directory.
- [ ] Self-reviewed the code before submitting.
- [ ] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Description**
A smaller version of the footer component is required.
The solution will need to only display the logo and a content defined by the user, everything displayed in the same row.

**Screenshots**
![image](https://github.com/dxc-technology/halstack-react/assets/33158831/790ec8ad-2d8d-4539-8b16-16148c3a3491)

**Closes #1792**

2024-02-01 14:46 UTC, Mil4n0r commented on lib/src/footer/Footer.tsx
> +    padding: ${(props) => (props?.variant !== "reduced" ? "24px 32px 24px 32px" : "12px 32px 12px 32px")};
The previous value was not right according to the Figma Doc.

2024-02-02 07:33 UTC, Mil4n0r commented
Converted to draft in order to discuss the naming of the variant prop.

2024-02-07 12:32 UTC, raquelarrojo requested changes

2024-02-07 12:32 UTC, raquelarrojo commented on lib/src/common/variables.ts
> +    childrenFontFamily: CoreTokens.type_sans,
We never have tokens for children, since this is not controlled by the user.

2024-02-07 12:32 UTC, raquelarrojo commented on lib/src/common/variables.ts
> +    reducedHeight: "40px",
We should not have `reducedHeight` token, since the height of the reduced footer should not be changed.

2024-02-07 12:32 UTC, raquelarrojo commented on lib/src/common/variables.ts
> +    tagGap: "20px",
`tagGap` token is not used anywhere.

2024-02-07 12:32 UTC, raquelarrojo commented on lib/src/footer/Footer.tsx
>    min-height: 16px;
`children` is always responsibility of the user. We do not controlled how the children are shown. The children can be anything, a sentence, a key:value... whatever. So the user is who must control how it is shown using our layout components.

2024-02-07 12:32 UTC, raquelarrojo commented on lib/src/footer/Footer.stories.tsx
> +          <div key={`tag${index}${tag.label}${tag.text}`}>
Layout components should be used for showing children, since this is controlled by the user.

2024-02-07 12:32 UTC, raquelarrojo commented on lib/src/footer/types.ts
> +  /**
This type is not used anywhere.

2024-02-07 12:32 UTC, raquelarrojo commented on website/screens/components/footer/specs/FooterSpecsPage.tsx
> +                </td>
These children tokens are not needed.

2024-02-07 12:32 UTC, raquelarrojo commented on website/screens/components/footer/specs/FooterSpecsPage.tsx
> +        title: "Height (reduced)",
I would include everything in a `Height` section, I mean:

Height:

- Default:
     (table with default tokens)
- Reduced:
    (table with reduced tokens)

2024-02-07 12:32 UTC, raquelarrojo commented on website/screens/components/footer/specs/FooterSpecsPage.tsx
> +            <thead>
Same with iconography.

2024-02-13 07:52 UTC, raquelarrojo approved these changes

2024-02-13 07:55 UTC, merged