Adding default tokens to ActionIcon
dxc-technology/halstack-react pull request #1818
Opened 2024-02-12 10:01 UTC by Jialecl

**Checklist**
_(Check off all the items before submitting)_

- [x] Build process is done without errors. All tests pass in the `/lib` directory.
- [x] Self-reviewed the code before submitting.
- [x] Meets accessibility standards.
- [x] Added/updated documentation to `/website` as needed.
- [x] Added/updated tests as needed.

**Purpose**
Some default styles were added in case there are no tokens available.
This will allow the component to be used in isolation.

2024-02-14 15:56 UTC, Mil4n0r requested changes
img in line 21 of `ActionIcon.tsx` should have an `alt` text.

Overall, more extra coverage could be added to the testing, both in this Component and `Button`, but I think this exceeds the scope of this task, I would create a separate PR for that.

Some ideas could be:
- Ensure that `onClick` action is not triggered when the Component is disabled.
- Verify that the tabIndex is being correctly set and ensure that keyboard interaction is working as expected.
- Test whether the component renders correctly when the icon prop is of type string or JSX.

2024-02-15 07:56 UTC, Jialecl commented
> * Verify that the tabIndex is being correctly set and ensure that keyboard interaction is working as expected.
The keyboard interaction is not needed to be tested, since it is the HTML behavior.

2024-02-15 16:04 UTC, Mil4n0r requested changes

2024-02-16 08:25 UTC, Jialecl commented on lib/src/action-icon/ActionIcon.tsx
>    ({ disabled = false, title, icon, onClick, tabIndex }, ref): JSX.Element => {
The props were correctly typed.
You can hover each prop to see the types coming from "./types"

2024-02-16 09:02 UTC, Mil4n0r commented on lib/src/action-icon/ActionIcon.tsx
>    ({ disabled = false, title, icon, onClick, tabIndex }, ref): JSX.Element => {
You are right, it was a bug in my IDE.

2024-02-16 09:12 UTC, Mil4n0r approved these changes

2024-02-16 09:13 UTC, merged