Modified tests extensions and added required types
dxc-technology/halstack-react pull request #1941
Opened 2024-04-04 13:39 UTC by Mil4n0r

**Checklist**
_(Check off all the items before submitting)_

- [ ] Build process is done without errors. All tests pass in the `/lib` directory.
- [ ] Self-reviewed the code before submitting.
- [ ] Meets accessibility standards.
- [ ] Added/updated documentation to `/website` as needed.
- [ ] Added/updated tests as needed.

**Description**
In the last introduced Components, we were already using tsx extension for tests. It was a good idea to convert all the existing functional and accessibility tests to tsx in order to improve consistency.

**Closes #1543**

2024-04-08 12:16 UTC, GomezIvann requested changes

2024-04-08 13:19 UTC, Mil4n0r commented on lib/src/table/types.ts
> +        icon?: never | undefined;
Yes, I thought the same but for some reason, when not adding undefined as an option, there was a TS problem saying that "never" was not matching "undefined" type, I will take another look at it.

2024-04-10 11:52 UTC, Mil4n0r commented on lib/src/table/types.ts
> +        icon?: never | undefined;
It seems that there was a problem with the type inference from TS, I did a workaround and now it seems to be solved.

2024-04-10 12:06 UTC, Mil4n0r commented on lib/src/table/types.ts
> +        icon?: never | undefined;
It seems to be a problem regarding TS type inference. I am not sure about how to solve it without manually typing the `actions` for both tests, this should not be needed...

![image](https://github.com/dxc-technology/halstack-react/assets/33158831/2255c298-2d97-44ed-9611-f4910f41551a)

2024-04-11 07:59 UTC, Mil4n0r commented on lib/src/table/types.ts
> +        icon?: never | undefined;
As the problem only happens in the test files, I have added the type manually to prevent wrong TS type inference.

2024-04-11 08:46 UTC, GomezIvann submitted a review, later dismissed

2024-04-11 10:13 UTC, GomezIvann approved these changes

2024-04-11 10:13 UTC, merged