Contextual menu updates & site improvements
dxc-technology/halstack-react pull request #2098
Opened 2024-10-02 07:58 UTC by GomezIvann

**Checklist**
_(Check off all the items before submitting)_

- [ ] The build process is done without errors. All tests pass in the `/lib` directory.
- [ ] Self-reviewed the code before submitting.
- [ ] Meets accessibility standards.
- [ ] Added/updated documentation to `/website` as needed.
- [ ] Added/updated tests as needed.

**Description**
Summary:
- Live examples have been updated. Now they use our toast and the code has been improved.
- Added release 14 to the releases page.
- **Contextual Menu**. Improved DOM tree structure. Also, I tried to add the Tooltip.

2024-10-02 11:00 UTC, Mil4n0r requested changes
The following disabledRules in `packages/lib/test/accessibility/rules/specific/contextual-menu/disabledRules.js` that are not covered by this solution:
- "aria-required-children": I think this is caused by a `ul` being a direct child of another `ul`. The following structure is expected instead:
```
<ul>
  <li>
    <ul>
      ...
    </ul>
  </li>
</ul>
```
- "aria-required-parent": There is a `menuitem` whose parent is not a ``
- "list": A list element has children with the role `menuitem`, which is not allowed as it is expected to be a `listitem`

After doing the appropiate changes to the roles, don't forget to swap the functional test checks accordingly.

2024-10-03 09:11 UTC, GomezIvann commented on packages/lib/src/contextual-menu/ItemAction.tsx
> +          >
Done!

2024-10-03 09:11 UTC, GomezIvann commented on packages/lib/src/contextual-menu/ContextualMenu.tsx
> -    <Fragment key={`section-${currentSectionIndex}`}>
Done!

2024-10-07 10:42 UTC, Mil4n0r approved these changes

2024-10-07 10:42 UTC, merged