BaseTypography removed
dxc-technology/halstack-react pull request #2124
Opened 2024-12-03 11:59 UTC by Jialecl

**Checklist**
_(Check off all the items before submitting)_

- [ ] Build process is done without errors. All tests pass in the `/lib` directory.
- [ ] Self-reviewed the code before submitting.
- [ ] Meets accessibility standards.
- [ ] Added/updated documentation to `/website` as needed.
- [ ] Added/updated tests as needed.

2024-12-04 12:18 UTC, GomezIvann requested changes

2024-12-04 12:18 UTC, GomezIvann commented on packages/lib/src/nav-tabs/Tab.tsx
> +            <LabelContainer
I don't understand this implementation. Why aren't you consuming the theme from the provider as in the other styled-components?

I know it is an internal component without a `ThemeProvider` but it should only be used outside the NavTabs, which do have such a provider, so this component would have access to it.

2024-12-04 12:18 UTC, GomezIvann commented on packages/lib/src/nav-tabs/Tab.tsx
> +  color: ${(props) => props.color};
Use `props.theme.xxx` instead and remove the props.

2024-12-04 12:18 UTC, GomezIvann commented on packages/lib/src/tabs/Tab.tsx
>                fontSize={colorsTheme.tabs.fontSize}
Same as in the Nav Tabs, don't use props and instead, consume the theme.

2024-12-04 12:18 UTC, GomezIvann commented on packages/lib/src/tabs/TabLegacy.tsx
> +  color: string;
Same as in the Nav Tabs, don't use props and instead, consume the theme.

2024-12-04 12:18 UTC, GomezIvann commented on packages/lib/src/paragraph/Paragraph.tsx
> +    <ParagraphContainer
Implement the component as we usually do Jiale, use the ThemeProvider!

`<ThemeProvider theme={colorsTheme.paragraph}>`

2024-12-05 12:16 UTC, GomezIvann commented on packages/lib/src/typography/Typography.tsx
> +const ValidTypographyTags = [
I did the change, we need this fix. We can discuss it later.

2024-12-05 12:16 UTC, GomezIvann commented on packages/lib/src/typography/Typography.tsx
> +const isValidTypography = (tag: keyof HTMLElementTagNameMap) => {
I did the change, we need this fix. We can discuss it later.

2024-12-05 12:44 UTC, Mil4n0r approved these changes

2024-12-05 12:53 UTC, GomezIvann approved these changes

2024-12-05 12:53 UTC, merged