[Minor] Advanced tokens for Checkbox component
dxc-technology/halstack-react pull request #303
Opened 2021-05-19 07:45 UTC by jsuarezgonz

2021-05-19 12:59 UTC, aweell commented on lib/src/common/variables.js
> +    checkGutter: "10px"
I suggest changing `checkGutter` to `checkLabelSpacing` since is more semantic

2021-05-19 13:01 UTC, aweell reviewed
Should we add tokens for the hover state? In order to provide a cue, like changing the bg or border color on hover?

2021-05-21 08:53 UTC, aweell requested changes
I saw you added `backgroundHoverColorChecked`, should we have one for unchecked also?

2021-05-21 10:25 UTC, jsuarezgonz commented
> I saw you added `backgroundHoverColorChecked`, should we have one for unchecked also?

There is no token referring to the 'unchecked' component, we only have the border in that case; that´s why I created a hover token for the border and not for the background.

2021-05-21 11:31 UTC, aweell approved these changes
🤘🏼

2021-05-25 08:06 UTC, merged