Types for Dropdown component
dxc-technology/halstack-react pull request #543
Opened 2022-01-24 11:56 UTC by marcialfps

Closes #540

2022-01-26 18:28 UTC, GomezIvann approved these changes

2022-01-31 12:51 UTC, marcialfps commented
## Changes

- Required props: `options` and `onSelectOption`.
- Required prop in each option: `value`.
- Documentation fixes.

2022-02-01 10:01 UTC, GomezIvann requested changes

2022-02-02 07:41 UTC, marcialfps commented on lib/src/dropdown/types.ts
> +  onSelectOption: (value: string) => void;
In this case we don't have an uncontrolled functionality. So, the component will not work if the user doesn't use that function.

2022-02-02 08:53 UTC, GomezIvann commented on lib/src/dropdown/types.ts
> +  onSelectOption: (value: string) => void;
Great!

2022-02-02 08:54 UTC, GomezIvann approved these changes

2022-02-02 09:08 UTC, merged