Types for Header component
dxc-technology/halstack-react pull request #581
Opened 2022-01-31 16:01 UTC by marcialfps

Closes #564 

## Changes

- Props types.
- Fix type errors:
   - `isResponsive` default value to false.
   - `ContentContainerComponent` receives children parameter.
- Documentation:
   - `content` prop type changed to `node`.

2022-02-01 11:07 UTC, GomezIvann commented
Should we remove _Icons.jsx_ and add the icons inside the component, as it is done in Select or TextInput? Just to remove the .jsx file.

2022-02-01 11:07 UTC, GomezIvann requested changes

2022-02-02 08:11 UTC, marcialfps commented on lib/src/header/Header.tsx
> +  const ContentContainerComponent = (props: any) => {
If I remove the parameter the following type error will be displayed:
![image](https://user-images.githubusercontent.com/35959222/152116498-7a1fe7a0-0f8d-4cf5-80bb-c9812a9703af.png)

2022-02-04 08:14 UTC, GomezIvann commented on lib/src/header/Header.tsx
> +  const ContentContainerComponent = (props: any) => {
Why does `ContentContainerComponent` have `responsiveContent(handleMenu)` both as a children and inside the function component? Children are not been used in the function component so maybe removing them is not a bad idea.

2022-02-04 10:15 UTC, marcialfps commented on lib/src/header/Header.tsx
> +  const ContentContainerComponent = (props: any) => {
Yes! I didn't realize. :expressionless: I changed it in the last commit.

2022-02-04 11:06 UTC, GomezIvann approved these changes

2022-02-04 11:08 UTC, merged