File-input visual fixes
dxc-technology/halstack-react pull request #691
Opened 2022-02-15 12:36 UTC by GomezIvann

2022-02-15 15:51 UTC, raquelarrojo approved these changes

2022-02-15 16:07 UTC, raquelarrojo requested changes
After removing min-height of error, the select in paginator is not aligned.

![image](https://user-images.githubusercontent.com/10975289/154100953-621be8a4-fe76-4171-8f41-9e897aa7994f.png)

2022-02-16 07:37 UTC, aweell commented
> After removing min-height of error, the select in paginator is not aligned.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/10975289/154100953-621be8a4-fe76-4171-8f41-9e897aa7994f.png)
> 
> 

How the file-input changes affect the select in the paginator?

2022-02-16 07:55 UTC, GomezIvann commented
> > After removing min-height of error, the select in paginator is not aligned.
> > ![image](https://user-images.githubusercontent.com/10975289/154100953-621be8a4-fe76-4171-8f41-9e897aa7994f.png)
> 
> How the file-input changes affect the select in the paginator?

This issue is caused by the change we did at the Select while correcting the `line-height`. By removing the min-height of the error message its reserved space now is gone. I fix it.

![image](https://user-images.githubusercontent.com/44321109/154218413-8aafb4e1-bec9-4e1f-9089-410cd707e0cb.png)

2022-02-16 09:48 UTC, raquelarrojo approved these changes

2022-02-16 09:48 UTC, merged