[Minor] Added disabled prop in tag component
dxc-technology/halstack-react pull request #731
Opened 2022-02-25 13:11 UTC by Lisa159

2022-02-25 14:41 UTC, aweell commented
What's the difference between the Storybook's examples "with icon" and "with large icon"?

![Screen Shot 2022-02-25 at 3 40 19 PM](https://user-images.githubusercontent.com/44420072/155734284-e82ea870-f396-47f2-a8a6-5747b96051eb.png)

2022-02-28 08:22 UTC, Lisa159 commented
> What's the difference between the Storybook's examples "with icon" and "with large icon"?
> 
> ![Screen Shot 2022-02-25 at 3 40 19 PM](https://user-images.githubusercontent.com/44420072/155734284-e82ea870-f396-47f2-a8a6-5747b96051eb.png)

Large icon is an icon bigger than the icon size from the specs. It is added to check it is escalating well (from 48px to 24px):

![image](https://user-images.githubusercontent.com/34685461/155948864-a1213611-7ef6-4e4a-9570-ce18748fd690.png)

2022-02-28 12:11 UTC, GomezIvann requested changes

2022-02-28 12:11 UTC, GomezIvann commented on lib/src/tag/Tag.stories.tsx
> +    <ExampleContainer pseudoState="pseudo-focus">
I think this test is functional rather than visual, we should have this in the jest set of tests.

2022-02-28 12:11 UTC, GomezIvann commented on lib/src/tag/Tag.stories.tsx
> +    <ExampleContainer pseudoState="pseudo-focus">
With a disabled test for the basic tag, tag with action and tag with the link I think it's enough.

2022-02-28 12:16 UTC, GomezIvann commented
More things to add to my review:

- Disabled Tag with `linkHref`, which displays as an anchor, works when it is clicked.
- Focus now doesn't work as usual, it displays the default HTML focus instead of our custom one. Also, the focus works with the disabled state:

![image](https://user-images.githubusercontent.com/44321109/155981837-63e2ec16-5d06-4b91-82b0-7e27ea73022a.png)

![image](https://user-images.githubusercontent.com/44321109/155981949-0fde0a01-6ab0-4485-8689-b34cfb933b1d.png)

As expected:

2022-03-01 10:55 UTC, aweell commented
> Does the disabled state make sense when the component is not clickable (anchor or link) and doesn't have hover or focus? What do you think about this @aweell?

If there's no interaction doesn't make much sense to have a disabled state.

2022-03-02 08:59 UTC, GomezIvann requested changes

2022-03-02 09:12 UTC, GomezIvann commented on lib/src/tag/Tag.stories.tsx
> +    <ExampleContainer pseudoState="pseudo-focus">
My proposal:

- Visual tests (storybook): Disabled as action, disabled as Link. We can keep having disabled + focused visual tests
- Jest tests: disabled tag is not clickable, both as a link and as an action (button).

2022-03-07 09:56 UTC, closed without merging