Radio group documentation update
dxc-technology/halstack-react pull request #810
Opened 2022-03-29 10:50 UTC by GomezIvann

Summary

- Documentation update, more examples and further error handling explanation.
- Added component to the theme builder.

2022-03-31 16:06 UTC, marcialfps requested changes
Comments about tests:

- _Initial render has correct aria attributes and tabIndex_ case. Add `aria-live` value.
- Simplify `.toHaveBeenCalled()` and `.toHaveBeenCalledWith(...)` in all tests.
- I think we need a new test case that verifies that all information is dispalyed, not just the aria attributes. For examples: label, optional radio group indicator, optional radio, error...

2022-04-01 07:09 UTC, GomezIvann commented on docs/src/pages/components/cdk-components/radio-group/RadioGroup.jsx
> +        </Example>
After a discussion about this, it was decided to add a bit of text to the example to make it more comprehensible for the user. In the beginning, the whole explanation was in the prop and was too long, making it less accessible from a user's point of view.

2022-04-01 07:22 UTC, GomezIvann commented on docs/src/pages/components/cdk-components/radio-group/examples/handlingErrors.js
> +    <div style={{ display: "flex", flexWrap: "wrap", margin: "36px" }}>
Done!

2022-04-01 07:30 UTC, GomezIvann commented
> Comments about tests:
> 
> * _Initial render has correct aria attributes and tabIndex_ case. Add `aria-live` value.
> * Simplify `.toHaveBeenCalled()` and `.toHaveBeenCalledWith(...)` in all tests.
> * I think we need a new test case that verifies that all information is dispalyed, not just the aria attributes. For examples: label, optional radio group indicator, optional radio, error...

I will answer one by one:

- You are right, I have already added it!
- What do you mean by simplify? It's not a random thing when I use one or another, I mean, `toHaveBeenCalledWith` is to ensure the events are not called more than once (which was a regular issue during development with the onFocus) and `toHaveBeenCalled` is for the rest of cases.
- I don't think this will add much value, since this is already been tested at chromatic stories.

2022-04-01 07:43 UTC, marcialfps commented
> * What do you mean by 'simplify? It's not a random thing when I use one or another, I mean, `toHaveBeenCalledWith` is to ensure the events are not called more than once (which was a regular issue during development with the onFocus) and `toHaveBeenCalled` is for the rest of cases.

By simplifying I mean that the second function is already checking that the function is called, so you only need to use `toHaveBeenCalledWith(...)`.

If you want to make sure it is called once you should use `toHaveBeenCalledTimes(n)`. 

> * I don't think this will add much value, since this is already been tested at chromatic stories.

I consider chromatic to be the test of the styles, but in this case we are testing the structure of the dom, so we need to verify that we have a label, optional markup...

2022-04-01 08:10 UTC, GomezIvann commented
> > * What do you mean by 'simplify? It's not a random thing when I use one or another, I mean, `toHaveBeenCalledWith` is to ensure the events are not called more than once (which was a regular issue during development with the onFocus) and `toHaveBeenCalled` is for the rest of cases.
> 
> By simplifying I mean that the second function is already checking that the function is called, so you only need to use `toHaveBeenCalledWith(...)`.
>
> If you want to make sure it is called once you should use `toHaveBeenCalledTimes(n)`.

I get it, I confused `toHaveBeenCalledWith` with `toHaveBeenCalledTimes(n)` while writing, you are right, I will fix this.

> 
> * I don't think this will add much value, since this is already been tested at chromatic stories.
> 
> I consider chromatic to be the test of the styles, but in this case we are testing the structure of the dom, so we need to verify that we have a label, optional text...

But, I continue without seeing the value it gives just checking it's presence in the DOM with jest. If there were an issue with this, the stories and chromatic would catch it and tell it to us, which is the main purpose of testing...

2022-04-01 10:30 UTC, marcialfps approved these changes

2022-04-01 10:42 UTC, merged