[Major] Updated tokens wizard
dxc-technology/halstack-react pull request #975
Opened 2022-05-19 11:38 UTC by Lisa159

2022-05-20 11:09 UTC, aweell requested changes

2022-05-23 09:04 UTC, Lisa159 commented on docs/src/pages/themeBuilder/themes/AdvancedTheme.json
> +    "disabledStepperBackgroundColor": "#f2f2f2",
Done

2022-05-25 07:42 UTC, aweell submitted a review, later dismissed

2022-05-26 11:18 UTC, Lisa159 commented on lib/src/common/variables.js
> +    stepFontColor: globalTokens.hal_black,
Done

2022-05-26 11:18 UTC, Lisa159 commented on lib/src/common/variables.js
> +    labelFontColor: globalTokens.hal_black,
Done

2022-05-26 11:28 UTC, Lisa159 commented
Added more rename of tokens:
- From `stepFontColor` to `visitedStepFontColor`.
- From `stepBackgroundColor` to `visitedStepBackgroundColor`.
- From `labelFontColor` to `visitedLabelFontColor`.
- From `activeLabelFontColor` to `selectedLabelFontColor`.
- From `helperTextFontColor` to `visitedHelperTextFontColor`.
- From `activeHelperTextFontColor` to `selectedHelperTextFontColor`.
- From `stepBorderColor` to `visitedStepBorderColor`.

2022-05-27 08:40 UTC, GomezIvann approved these changes

2022-05-27 08:41 UTC, merged